---
- name: Install nginx
  package:
    name: 
      - "@nginx"
      - yum-utils
      - epel-release
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Add firewall rules
  command: firewall-cmd --add-service=http --permanent
  notify:
    - restart firewalld

- name: create repo directory
  file:
    path: {{repo_location}}
    state: directory
    owner: nginx
    recurse: yes

- name: Copy update-repo daily cron script
  template:
    src: update-repo.j2
    dest: /etc/cron.daily/update-repo
    mode: 755

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/centos.conf
  notify:
    - restart nginx

- name: permissions for repo location
  shell: "semanage fcontext -a -t httpd_sys_content_t '{{repo_location}}(/.*)?'"
  ignore_errors: yes

- name: Restore SELinux Context
  shell: "restorecon -Rv {{repo_location}}"

- name: Set repo hostname
  hostname:
    name: "{{ repo_hostname }}"